# Generated by Django 2.2.6 on 2019-10-16 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensurance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200, verbose_name='Название услуги')),
            ],
        ),
    ]
